CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at INTEGER NOT NULL,
  checksum TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_test_runs (id TEXT PRIMARY KEY, name TEXT NOT NULL, passed INTEGER NOT NULL, value TEXT NOT NULL, created_at INTEGER NOT NULL);
